### ISSUE TITLE
Support for CS2

### ISSUE THREAD

**Issue by zhuchangzhan** [hitranonline/hapi#22]
Hello, I see that the line list for CS2 is released on https://hitran.org/lbl/, will hapi be updated to support calculating cross section for CS2?

Thanks!

**Comment by erwanp** [comment]
@zhuchangzhan Roman Kochanov told me a HAPI2 version was coming soon, so it may be included!

**Comment by RomanKochanov** [comment]
Hello,
The support of the CS2 molecule is also planned in the upcoming minor update of HAPI.
Thanks for the feedback!
Best wishes,
Roman
